apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpa-admission-controller
  namespace: kube-system
  labels:
    application: vpa-admission-controller
    version: v0.2.0
spec:
  replicas: 1
  selector:
    matchLabels:
      application: vpa-admission-controller
  template:
    metadata:
      labels:
        application: vpa-admission-controller
        version: v0.2.0
    spec:
      priorityClassName: system-cluster-critical
      serviceAccountName: system
      containers:
      - name: admission-controller
        # image: k8s.gcr.io/vpa-admission-controller:0.2.0
        # fixes: https://github.com/maartenvandenbogaard/autoscaler/commit/754bced8e36db0f78fbd21db70f2ab5eeda887b0
        image: mikkeloscar/vpa-admission-controller:v0.2.1
        volumeMounts:
        - name: tls-certs
          mountPath: "/etc/tls-certs"
          readOnly: true
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 200Mi
        ports:
        - containerPort: 8000
      volumes:
      - name: tls-certs
        secret:
          secretName: vpa-tls-certs
