apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpa-recommender
  namespace: kube-system
  labels:
    application: vpa-recommender
    version: v0.2.0
spec:
  replicas: 1
  selector:
    matchLabels:
      application: vpa-recommender
  template:
    metadata:
      labels:
        application: vpa-recommender
        version: v0.2.0
    spec:
      priorityClassName: system-cluster-critical
      serviceAccountName: system
      containers:
      - name: recommender
        image: k8s.gcr.io/vpa-recommender:0.2.0
        resources:
          limits:
            cpu: 50m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 500Mi
        ports:
        - containerPort: 8080
