apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpa-updater
  namespace: kube-system
  labels:
    application: vpa-updater
    version: v0.2.0
spec:
  replicas: 1
  selector:
    matchLabels:
      application: vpa-updater
  template:
    metadata:
      labels:
        application: vpa-updater
        version: v0.2.0
    spec:
      priorityClassName: system-cluster-critical
      serviceAccountName: system
      containers:
      - name: updater
        # image: k8s.gcr.io/vpa-updater:0.2.0
        image: mikkeloscar/vpa-updater:v0.2.1
        command: ["./updater"]
        args:
        - --min-replicas=1
        # from: https://github.com/kubernetes/autoscaler/blob/58e107abbbae98cdcce15d905ea90e0dc0a8426a/vertical-pod-autoscaler/pkg/updater/Dockerfile#L21
        - --v=4
        - --stderrthreshold=info
        resources:
          limits:
            cpu: 50m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 500Mi
        ports:
        - containerPort: 8080
